#iteration კოდის გამეორებაა  მაგალითად რეგისტრაცია sequencing არის კოდის რიგრიგობით დაწერა მაგალითად კიბე selection არის კოდის არჩევანი როგორც სადმე წასვლა
print(5>4 and 7>5)
print(6<7 or 6>7)
print(13>12 or 7>8)
print(5>8 and 9<8)
print(7<8 and 6.8 < 7.8)
print (not 9<7 or 9<7)
print(8>9 or 4<5)
print(7==7 and 6>7)
print(4>8 or 8<9)
print(9<8 or 9>0)
name =input("enter your name : ")
age =int(input("enter your age : "))
hight =float(input("enter your hight : "))
print(name , age , hight)